# Generated by Django 5.0.3 on 2024-03-09 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='ПРИОРИТЕТ')),
                ('name', models.CharField(max_length=200, verbose_name='НАИМЕНОВАНИЕ')),
                ('description', models.TextField(max_length=200, verbose_name='ОПИСАНИЕ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('img', models.ImageField(upload_to='', verbose_name='IMG')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ЦЕНА')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='СКИДКА %')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='КАТЕГОРИЯ', to='category.category')),
                ('recommend', models.ManyToManyField(blank=True, to='product.product', verbose_name='Рекомендации')),
                ('use', models.ManyToManyField(blank=True, related_name='ОБЛАСТЬ', to='category.use')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['priority'],
            },
        ),
    ]
