# Generated by Django 5.0.3 on 2024-03-10 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='ОПИСАНИЕ'),
        ),
    ]
