# Generated by Django 5.0.3 on 2024-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_img'),
        ('product', '0003_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommend',
            field=models.ManyToManyField(null=True, to='product.product', verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='СКИДКА %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Описание', max_length=200, verbose_name='ОПИСАНИЕ КРАТКОЕ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use',
            field=models.ManyToManyField(null=True, related_name='ОБЛАСТЬ', to='category.use'),
        ),
    ]
