# Generated by Django 5.0.3 on 2024-03-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_img'),
        ('product', '0004_alter_product_img_alter_product_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='КАТЕГОРИЯ', to='category.category'),
        ),
    ]
