# Generated by Django 5.0.3 on 2024-03-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_img'),
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommend',
            field=models.ManyToManyField(blank=True, null=True, to='product.product', verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='СКИДКА %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use',
            field=models.ManyToManyField(blank=True, null=True, related_name='ОБЛАСТЬ', to='category.use'),
        ),
    ]
