# Generated by Django 5.0.3 on 2024-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_img_alter_product_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='ЦЕНА'),
        ),
    ]
