# Generated by Django 5.0.3 on 2024-03-11 11:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_sub_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='ОПИСАНИЕ'),
        ),
    ]
