# Generated by Django 5.0.3 on 2024-03-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='use',
        ),
    ]
