# Generated by Django 5.0.3 on 2024-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_alter_subcategory_category'),
        ('product', '0016_remove_product_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use',
            field=models.ManyToManyField(blank=True, null=True, related_name='ОБЛАСТЬ', to='category.use'),
        ),
    ]
