# Generated by Django 5.0.3 on 2024-03-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='use',
            new_name='uses',
        ),
    ]
