# Generated by Django 5.0.3 on 2024-03-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_additional_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='included_in_package',
        ),
    ]
