# Generated by Django 5.0.3 on 2024-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_included_in_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag_one',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ТЕГ 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_two',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ТЕГ 2'),
        ),
    ]
