# Generated by Django 5.0.3 on 2024-03-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0028_alter_subcategory_category_twosubcategory_and_more'),
        ('product', '0024_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='two_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.twosubcategory', to_field='slug'),
        ),
    ]
