# Generated by Django 5.0.3 on 2024-03-16 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_product_additional_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='ИМЯ')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.CreateModel(
            name='СharacteristicsItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='product.сharacteristic')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.product')),
            ],
            options={
                'verbose_name': 'Характеристика Продукта',
                'verbose_name_plural': 'Характеристики Продукта',
            },
        ),
    ]
