# Generated by Django 5.0.3 on 2024-03-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_сharacteristic_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СharacteristicsItems',
            new_name='СharacteristicItems',
        ),
    ]
