# Generated by Django 5.0.3 on 2024-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0033_alter_category_img_alter_use_img'),
        ('product', '0031_remove_productimage_my_model_productimage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='КАРТИНКИ', to='category.use'),
        ),
    ]
