# Generated by Django 5.0.3 on 2024-03-20 19:29

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thump',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='public/img/product/thumps'),
        ),
    ]
