# Generated by Django 5.0.3 on 2024-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productimage_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-main'], 'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL Видео'),
        ),
    ]
