# Generated by Django 5.0.3 on 2024-03-09 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='НАЗВАНИЕ')),
                ('description', models.TextField(max_length=200, verbose_name='ОПИСАНИЕ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('img', models.ImageField(upload_to='', verbose_name='IMG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='НАЗВАНИЕ')),
                ('description', models.TextField(max_length=200, verbose_name='ОПИСАНИЕ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('img', models.ImageField(upload_to='', verbose_name='IMG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
