# Generated by Django 5.0.3 on 2024-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='IMG'),
        ),
    ]
