# Generated by Django 5.0.3 on 2024-03-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_use_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='use',
            options={'verbose_name': 'Область применения', 'verbose_name_plural': 'Области применения'},
        ),
    ]
