# Generated by Django 5.0.3 on 2024-03-11 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_options_alter_use_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='НАЗВАНИЕ')),
                ('description', models.TextField(max_length=200, verbose_name='ОПИСАНИЕ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='IMG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ПодКатегория',
                'verbose_name_plural': 'ПодКатегории',
            },
        ),
    ]
