# Generated by Django 5.0.3 on 2024-03-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='description',
            field=models.TextField(verbose_name='ОПИСАНИЕ'),
        ),
    ]
