# Generated by Django 5.0.3 on 2024-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='ОПИСАНИЕ'),
        ),
    ]
