# Generated by Django 5.0.3 on 2024-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='short_name',
            field=models.CharField(max_length=200, null=True, verbose_name='КОРОТКИЕ НАЗВАНИЕ'),
        ),
    ]
