# Generated by Django 5.0.3 on 2024-03-15 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_use_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='НАЗВАНИЕ')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='ОПИСАНИЕ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='IMG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='КАТЕГОРИЯ', to='category.subcategory', to_field='slug')),
            ],
            options={
                'verbose_name': 'ПодКатегория',
                'verbose_name_plural': 'ПодКатегории',
            },
        ),
    ]
