# Generated by Django 5.0.3 on 2024-03-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0026_ssubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssubcategory',
            options={'verbose_name': 'ПодКатегория 2', 'verbose_name_plural': 'ПодКатегории 2'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='category.category', to_field='slug'),
        ),
    ]
