# Generated by Django 5.0.3 on 2024-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0028_alter_subcategory_category_twosubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, upload_to='category/', verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='twosubcategory',
            name='img',
            field=models.ImageField(blank=True, upload_to='uses/', verbose_name='IMG'),
        ),
    ]
