# Generated by Django 5.0.3 on 2024-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_alter_twosubcategory_img_alter_use_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/category/', verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='use',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/uses/', verbose_name='IMG'),
        ),
    ]
